package:
  name: openensembles 
  version: "2.0.0"

source:
  git_rev: OpenEnsembles-v2.0.0
  git_url: https://github.com/NaegleLab/OpenEnsembles

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python=3.7.*
    - setuptools
    - hdbscan=0.8.*
    - ipykernel=5.1.*
    - ipython=7.21.*
    - jupyter=1.0.*
    - matplotlib=3.3*
    - nb_conda_kernels=2.2.*
    - nbclient=0.5.*
    - networkx=2.5
    - notebook=6.0.*
    - numpy=1.19.*
    - pandas=1.2.*
    - scikit-learn=0.24.*
    - scipy=1.6.*

  run:
    - python

about:
  home: https://github.com/NaegleLab/OpenEnsembles
  license: GNU General Public License v3
  license_file: license.txt
